spring.application.name=fantasyfootballapp
server.port=8443

# Generate the keystore.p12 at time of deployment
# server.ssl.enabled=true
# server.ssl.key-store=classpath:keystore.p12 
# server.ssl.key-store-password=yourpassword
# server.ssl.keyStoreType=PKCS12
# server.ssl.keyAlias=tomcat